version: '3'

services:
  web:
    container_name: web
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - 8000:80
    volumes:
      - ./web/conf.d:/etc/nginx/conf.d
    networks:
      - nginx_network

  app:
    container_name: app
    depends_on:
      - selenium
      - tinc
    build:
      context: ./app
      dockerfile: Dockerfile
    expose:
      - 8000
    networks:
      - nginx_network
    volumes:
      - ./app:/opt/app

  selenium:
    container_name: selenium
    image: seleniarm/standalone-firefox:4.0.0-beta-1-20210215
    ports:
      - 4444
    volumes:
      - /dev/shm:/dev/shm

  tinc:
    container_name: tinc
    image: jenserat/tinc:latest
    ports:
      - 655
    volumes:
      - /erc/tinc:/etc/tinc

networks:
  nginx_network:
    driver: bridge
